services:
  db:
    image: postgres:18-alpine
    container_name: my-cloud-db
    environment:
      - POSTGRES_USER=mycloud
      - POSTGRES_PASSWORD=mycloudpassword
      - POSTGRES_DB=mycloud_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-cloud-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mycloud_db
      SPRING_DATASOURCE_USERNAME: mycloud
      SPRING_DATASOURCE_PASSWORD: mycloudpassword
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: my-cloud-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
