services:
  db:
    image: postgres:18-alpine
    container_name: my-cloud-db-dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: my-cloud-rabbitmq-dev
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: my-cloud-backend-dev
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - THUMBNAIL_SECRET=${THUMBNAIL_SECRET}
      - THUMBNAIL_CALLBACK_SECRET=${THUMBNAIL_CALLBACK_SECRET}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - DDL_AUTO_VALUE=${DDL_AUTO_VALUE_DEV}
      - ROOT_DISPLAYNAME=${ROOT_DISPLAYNAME}
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      - ROOT_EMAIL=${ROOT_EMAIL}
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
      - ./backend/pom.xml:/app/pom.xml
      - ${DISK_PATH}:/app/uploads
      - maven-repo:/root/.m2
    depends_on:
      - db
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: my-cloud-frontend-dev
    environment:
      - VITE_API_URL=/api
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  thumbnail-worker:
    build:
      context: ./thumbnail-service
      dockerfile: Dockerfile
    container_name: my-cloud-thumbnail-dev
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      BACKEND_URL: http://backend:8080
      THUMBNAIL_CALLBACK_SECRET: ${THUMBNAIL_CALLBACK_SECRET}
    volumes:
      - ${DISK_PATH}:/app/uploads
    depends_on:
      - rabbitmq
      - backend

volumes:
  maven-repo: